import type { Metadata } from "next";
import { Archivo_Black, Questrial } from 'next/font/google';
import "./globals.css";

const archivoBlack = Archivo_Black({
  weight: '400', // 
  subsets: ['latin'],
  variable: '--font-archivo-black',
  display: 'swap', 
});

const questrial = Questrial({
  weight: '400', // Questrial também geralmente só tem um peso (400)
  subsets: ['latin'],
  variable: '--font-questrial', // Nome da variável CSS para Questrial
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivoBlack.variable} ${questrial.variable} antialiased`}
      >
       <main className="">
         {children}
       </main>
      </body>
    </html>
  );
}
